export const GET_APP_VERSION = 'GET_APP_VERSION';
export const SET_APP_VERSION = 'SET_APP_VERSION';

export const INIT_LOGIN = 'INIT_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_STATUS = 'CHANGE_PASSWORD_STATUS';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_STATUS = 'FORGOT_PASSWORD_STATUS';

export const INIT_LOGOUT = 'INIT_LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const SET_INITIAL_STATE_NULL_AUTH = 'SET_INITIAL_STATE_NULL_AUTH';
export const SET_INITIAL_STATE_NULL_INCOMEREPORT =
  'SET_INITIAL_STATE_NULL_INCOMEREPORT';
export const SET_INITIAL_STATE_NULL_INVESTMENT =
  'SET_INITIAL_STATE_NULL_INVESTMENT';
export const SET_INITIAL_STATE_NULL_KNOWLEDGE_CENTER =
  'SET_INITIAL_STATE_NULL_KNOWLEDGE_CENTER';
export const SET_INITIAL_STATE_NULL_LEVERAGE =
  'SET_INITIAL_STATE_NULL_LEVERAGE';
export const SET_INITIAL_STATE_NULL_PROFILE = 'SET_INITIAL_STATE_NULL_PROFILE';
export const SET_INITIAL_STATE_NULL_REWARDS = 'SET_INITIAL_STATE_NULL_REWARDS';
export const SET_INITIAL_STATE_NULL_WALLET = 'SET_INITIAL_STATE_NULL_WALLET';
export const SET_INITIAL_STATE_NULL_FORGOT = 'SET_INITIAL_STATE_NULL_FORGOT';

export const GET_COUNTRY_LIST = 'GET_COUNTRY_LIST';
export const PUT_COUNTRY_LIST = 'PUT_COUNTRY_LIST';

export const GET_SPONSOR_NAME = 'GET_SPONSOR_NAME';
export const PUT_SPONSOR_NAME = 'PUT_SPONSOR_NAME';

export const INIT_SIGNUP = 'INIT_SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const PUT_USER_DETAILS = 'PUT_USER_DETAILS';

export const GET_APPROVERS = 'GET_APPROVERS';
export const PUT_APPROVERS = 'PUT_APPROVERS';

export const UPDATE_MY_PROFILE = 'UPDATE_MY_PROFILE';
export const UPDATE_MY_PROFILE_STATUS = 'UPDATE_MY_PROFILE_STATUS';

export const GET_FAST_TRACK_QUALIFIER = 'GET_FAST_TRACK_QUALIFIER';
export const PUT_FAST_TRACK_QUALIFIER = 'PUT_FAST_TRACK_QUALIFIER';

export const GET_DASHBOARD_INCOME_DETAIL = 'GET_DASHBOARD_INCOME_DETAIL';
export const PUT_DASHBOARD_INCOME_DETAIL = 'PUT_DASHBOARD_INCOME_DETAIL';

export const GET_MANAGEMENT_PERFORMANCE_INCOME =
  'GET_MANAGEMENT_PERFORMANCE_INCOME';
export const PUT_MANAGEMENT_PERFORMANCE_INCOME =
  'PUT_MANAGEMENT_PERFORMANCE_INCOME';

export const GET_PERFORMANCE_INCOME = 'GET_PERFORMANCE_INCOME';
export const PUT_PERFORMANCE_INCOME = 'PUT_PERFORMANCE_INCOME';

export const GET_CORPORATE_PERFORMANCE_INCOME =
  'GET_CORPORATE_PERFORMANCE_INCOME';
export const PUT_CORPORATE_PERFORMANCE_INCOME =
  'PUT_CORPORATE_PERFORMANCE_INCOME';

export const GET_ROI_INCOME = 'GET_ROI_INCOME';
export const PUT_ROI_INCOME = 'PUT_ROI_INCOME';

export const GET_BUSINESS_FLUSH_REPORT = 'GET_BUSINESS_FLUSH_REPORT';
export const PUT_BUSINESS_FLUSH_REPORT = 'PUT_BUSINESS_FLUSH_REPORT';

export const GET_LEVELWISE_PERFORMANCE_INCOME =
  'GET_LEVELWISE_PERFORMANCE_INCOME';
export const PUT_LEVELWISE_PERFORMANCE_INCOME =
  'PUT_LEVELWISE_PERFORMANCE_INCOME';

export const GET_WEEKWISE_PERFORMANCE_INCOME =
  'GET_WEEKWISE_PERFORMANCE_INCOME';
export const PUT_WEEKWISE_PERFORMANCE_INCOME =
  'PUT_WEEKWISE_PERFORMANCE_INCOME';

// Wallet
export const ADD_FUND_TO_WALLET_VIA_MDTX = 'ADD_FUND_TO_WALLET_VIA_MDTX';
export const ADD_FUND_TO_WALLET_VIA_MDTX_STATUS =
  'ADD_FUND_TO_WALLET_VIA_MDTX_STATUS';

export const ADD_FUND_TO_WALLET_VIA_USDT = 'ADD_FUND_TO_WALLET_VIA_USDT';
export const ADD_FUND_TO_WALLET_VIA_USDT_STATUS =
  'ADD_FUND_TO_WALLET_VIA_USDT_STATUS';

export const GET_ADD_FUND_HISTORY = 'GET_ADD_FUND_HISTORY';
export const PUT_ADD_FUND_HISTORY = 'PUT_ADD_FUND_HISTORY';

export const GET_WITHDRAWAL_FUND = 'GET_WITHDRAWAL_FUND';
export const PUT_WITHDRAWAL_FUND = 'PUT_WITHDRAWAL_FUND';

export const GET_WITHDRAWAL_HISTORY = 'GET_WITHDRAWAL_HISTORY';
export const PUT_WITHDRAWAL_HISTORY = 'PUT_WITHDRAWAL_HISTORY';

export const GET_INVESTMENT_FUND_HISTORY = 'GET_INVESTMENT_FUND_HISTORY';
export const PUT_INVESTMENT_FUND_HISTORY = 'PUT_INVESTMENT_FUND_HISTORY';

export const GET_CASH_WALLET_HISTORY = 'GET_CASH_WALLET_HISTORY';
export const PUT_CASH_WALLET_HISTORY = 'PUT_CASH_WALLET_HISTORY';

export const TRANSFER_FUND_TO_OTHER = 'TRANSFER_FUND_TO_OTHER';
export const TRANSFER_FUND_TO_OTHER_STATUS = 'TRANSFER_FUND_TO_OTHER_STATUS';

export const GET_TRANSFER_FUND_REPORT = 'GET_TRANSFER_FUND_REPORT';
export const PUT_TRANSFER_FUND_REPORT = 'PUT_TRANSFER_FUND_REPORT';

//

export const WITHDRAWAL_REQUEST_USDT = 'WITHDRAWAL_REQUEST_USDT';
export const WITHDRAWAL_REQUEST_USDT_STATUS = 'WITHDRAWAL_REQUEST_USDT_STATUS';
export const WITHDRAWAL_REQUEST_MDTX = 'WITHDRAWAL_REQUEST_MDTX';
export const WITHDRAWAL_REQUEST_MDTX_STATUS = 'WITHDRAWAL_REQUEST_MDTX_STATUS';
export const WITHDRAWAL_INVEST_COMPOUNDING = 'WITHDRAWAL_INVEST_COMPOUNDING';
export const WITHDRAWAL_INVEST_COMPOUNDING_STATUS =
  'WITHDRAWAL_INVEST_COMPOUNDING_STATUS';
export const TRANSFER_FUND_TO_INVESTMENT_WALLET =
  'TRANSFER_FUND_TO_INVESTMENT_WALLET';
export const TRANSFER_FUND_TO_INVESTMENT_WALLET_STATUS =
  'TRANSFER_FUND_TO_INVESTMENT_WALLET_STATUS';

export const GET_INVESTMENT_WALLET_BALANCE = 'GET_INVESTMENT_WALLET_BALANCE';
export const PUT_INVESTMENT_WALLET_BALANCE = 'PUT_INVESTMENT_WALLET_BALANCE';

export const GET_INCOME_WALLET_BALANCE = 'GET_INCOME_WALLET_BALANCE';
export const PUT_INCOME_WALLET_BALANCE = 'PUT_INCOME_WALLET_BALANCE';

export const GET_TOTAL_FUND_WALLET_BALANCE = 'GET_TOTAL_FUND_WALLET_BALANCE';
export const PUT_TOTAL_FUND_WALLET_BALANCE = 'PUT_TOTAL_FUND_WALLET_BALANCE';

export const GET_MDTX_SECU_WALLET_BALANCE = 'GET_MDTX_SECU_WALLET_BALANCE';
export const PUT_MDTX_SECU_WALLET_BALANCE = 'PUT_MDTX_SECU_WALLET_BALANCE';

export const RELOAD_ALL_WALLET_BALANCE = 'RELOAD_ALL_WALLET_BALANCE';
export const RELOAD_ALL_WALLET_BALANCE_STATUS =
  'RELOAD_ALL_WALLET_BALANCE_STATUS';

export const GET_WITHDRAWAL_ON_OFF = 'GET_WITHDRAWAL_ON_OFF';
export const PUT_WITHDRAWAL_ON_OFF = 'PUT_WITHDRAWAL_ON_OFF';
// Investments
export const GET_MY_INVESTMENTS = 'GET_MY_INVESTMENTS';
export const PUT_MY_INVESTMENTS = 'PUT_MY_INVESTMENTS';

export const GET_MY_COMPOUND_INVESTMENTS = 'GET_MY_COMPOUND_INVESTMENTS';
export const PUT_MY_COMPOUND_INVESTMENTS = 'PUT_MY_COMPOUND_INVESTMENTS';

export const GET_INVESTMENT_PACKAGE = 'GET_INVESTMENT_PACKAGE';
export const PUT_INVESTMENT_PACKAGE = 'PUT_INVESTMENT_PACKAGE';

export const MAKE_INVESTMENT = 'MAKE_INVESTMENT';
export const MAKE_INVESTMENT_STATUS = 'MAKE_INVESTMENT_STATUS';

// Leverage
export const GET_MY_LEVERAGE = 'GET_MY_LEVERAGE';
export const PUT_MY_LEVERAGE = 'PUT_MY_LEVERAGE';

export const GET_TEAM_LEVERAGE = 'GET_TEAM_LEVERAGE';
export const PUT_TEAM_LEVERAGE = 'PUT_TEAM_LEVERAGE';

// club and rewards
export const GET_MONTHLY_RANKING_CLUB = 'GET_MONTHLY_RANKING_CLUB';
export const PUT_MONTHLY_RANKING_CLUB = 'PUT_MONTHLY_RANKING_CLUB';

export const GET_LIFETIME_RANKING_REWARDS = 'GET_LIFETIME_RANKING_REWARDS';
export const PUT_LIFETIME_RANKING_REWARDS = 'PUT_LIFETIME_RANKING_REWARDS';

export const GET_ZOOM_REWARD_LIST = 'GET_ZOOM_REWARD_LIST';
export const PUT_ZOOM_REWARD_LIST = 'PUT_ZOOM_REWARD_LIST';

export const CLAIM_MDTX_REWARD = 'CLAIM_MDTX_REWARD';
export const CLAIM_MDTX_REWARD_STATUS = 'CLAIM_MDTX_REWARD_STATUS';

export const GET_ROI_ON_OFF = 'GET_ROI_ON_OFF';
export const PUT_ROI_ON_OFF = 'PUT_ROI_ON_OFF';

// profiles
export const GET_SUB_ACCOUNTS = 'GET_SUB_ACCOUNTS';
export const PUT_SUB_ACCOUNTS = 'PUT_SUB_ACCOUNTS';

export const GET_MY_TICKETS = 'GET_MY_TICKETS';
export const PUT_MY_TICKETS = 'PUT_MY_TICKETS';

export const SUBMIT_POS_REQUEST = 'SUBMIT_POS_REQUEST';
export const SUBMIT_POS_REQUEST_STATUS = 'SUBMIT_POS_REQUEST_STATUS';

export const SUBMIT_SUPPORT_REQUEST = 'SUBMIT_SUPPORT_REQUEST';
export const SUBMIT_SUPPORT_REQUEST_STATUS = 'SUBMIT_SUPPORT_REQUEST_STATUS';

export const SUBMIT_CHANGE_LOGIN_PASSWORD = 'SUBMIT_CHANGE_LOGIN_PASSWORD';
export const SUBMIT_CHANGE_LOGIN_PASSWORD_STATUS =
  'SUBMIT_CHANGE_LOGIN_PASSWORD_STATUS';

export const SUBMIT_CHANGE_WALLET_PASSWORD = 'SUBMIT_CHANGE_WALLET_PASSWORD';
export const SUBMIT_CHANGE_WALLET_PASSWORD_STATUS =
  'SUBMIT_CHANGE_WALLET_PASSWORD_STATUS';

export const SUBMIT_UPDATE_PROFILE = 'SUBMIT_UPDATE_PROFILE';
export const SUBMIT_UPDATE_PROFILE_STATUS = 'SUBMIT_UPDATE_PROFILE_STATUS';

// Knowledgecenter list
export const GET_KNOWLEDGE_CENTER_LIST = 'GET_KNOWLEDGE_CENTER_LIST';
export const PUT_KNOWLEDGE_CENTER_LIST = 'PUT_KNOWLEDGE_CENTER_LIST';

export const UPDATE_EMAIL_ADDRESS = 'UPDATE_EMAIL_ADDRESS';
export const UPDATE_EMAIL_ADDRESS_STATUS = 'UPDATE_EMAIL_ADDRESS_STATUS';

export const VERIFY_EMAIL_OTP = 'VERIFY_EMAIL_OTP';
export const VERIFY_EMAIL_OTP_STATUS = 'VERIFY_EMAIL_OTP_STATUS';

export const SET_2FA_AUTH = 'SET_2FA_AUTH';
export const SET_2FA_AUTH_STATUS = 'SET_2FA_AUTH_STATUS';
